const brewData = [
 {id:"10-56-brewing-company-knox",name:"Brewing Company",brewery_type:"micro",street:"400 Brown Cir", about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
{id:"10-barrel-brewing-co-bend-1",name:"Barrel Brewing Co",brewery_type:"large",street:"62970 18th St", about: "Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Velit ut tortor pretium viverra suspendisse potenti. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Dictum non consectetur a erat nam. Nisl tincidunt eget nullam non nisi. Sit amet consectetur adipiscing elit pellentesque habitant morbi. "},
{id:"10-barrel-brewing-co-bend-2",name:"BB Brewing Co",brewery_type:"large",street:"1135 NW Galveston Ave Ste B", about: "Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Velit ut tortor pretium viverra suspendisse potenti. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Dictum non consectetur a erat nam. Nisl tincidunt eget nullam non nisi. Sit amet consectetur adipiscing elit pellentesque habitant morbi."},
{id:"10-barrel-brewing-co-bend-pub-bend",name:"Bros and Barrels Brewing Co - Bend Pub",brewery_type:"large",street:"62950 NE 18th St", about: "Amet venenatis urna cursus eget. Urna id volutpat lacus laoreet. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Aliquam etiam erat velit scelerisque. Id faucibus nisl tincidunt eget nullam non. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Interdum varius sit amet mattis vulputate enim nulla. Pretium lectus quam id leo in. Semper auctor neque vitae tempus quam pellentesque nec nam."},
{id:"10-barrel-brewing-co-boise-boise",name:"Barreling Brewing Co - Boise",brewery_type:"large",street:"826 W Bannock St",about:"In nulla posuere sollicitudin aliquam ultrices. Dignissim suspendisse in est ante in. Ut ornare lectus sit amet est placerat in egestas. Suscipit adipiscing bibendum est ultricies. Sed risus ultricies tristique nulla aliquet enim tortor at. Vulputate odio ut enim blandit. Semper viverra nam libero justo laoreet sit amet cursus. Viverra adipiscing at in tellus integer feugiat. Sit amet luctus venenatis lectus magna fringilla. Dictum at tempor commodo ullamcorper. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper."},{id:"10-barrel-brewing-co-denver-denver",name:"Barely Brewing Co - Denver",brewery_type:"large",street:"2620 Walnut St", about:"Nisi porta lorem mollis aliquam ut. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Nullam ac tortor vitae purus faucibus ornare suspendisse. Elementum nibh tellus molestie nunc non blandit massa. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Quam lacus suspendisse faucibus interdum. Bibendum at varius vel pharetra vel turpis nunc eget lorem. "},
{id:"10-barrel-brewing-co-portland",name:"Bruster Brewing Co",brewery_type:"large",street:"1411 NW Flanders St", about:"Non sodales neque sodales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam vulputate dignissim. "},
{id:"10-barrel-brewing-co-san-diego",name:"Rooster Brewing Co", brewery_type:"large",street:"1501 E St", street:"490 Mill St",about:"dales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam vulputate dignissim. Tincidunt dui ut ornare lectus sit amet est placerat in. Quam vulputate dignissim suspendisse in est ante in. "},
{id:"101-brewery-quilcene",name:"101 Brewery",brewery_type:"brewpub", street:"294793 US Highway 101", about:"Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Nullam ac tortor vitae purus faucibus ornare suspendisse. Elementum nibh tellus molestie nunc non blandit massa."},
{id:"101-north-brewing-company-petaluma",name:"101 North Brewing Company",brewery_type:"micro", street :"1304 Scott St Ste D", about: "Non sodales neque sodales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam vulputate dignissim."},{id:"105-west-brewing-co-castle-rock",name:"West Brewing Co",brewery_type:"micro",street:"1043 Park St", about: "Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Nullam ac tortor vitae purus faucibus ornare suspendisse. Elementum nibh tellus molestie nunc non blandit massa. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi."},
{id:"10k-brewing-anoka",name:"10K Brewing",brewery_type:"micro",street:"2005 2nd Ave",about:" Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Aliquam etiam erat velit scelerisque. Id faucibus nisl tincidunt eget nullam non. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin."},
{id:"10th-district-brewing-company-abington",name:"10th District Brewing Company",brewery_type:"micro",street:"491 Washington St", about:" Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Aliquam etiam erat velit scelerisque. Id faucibus nisl tincidunt eget nullam non. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin."},
{id:"11-below-brewing-company-houston",name:"11 Below Brewing Company",brewery_type:"micro", street:"6820 Bourgeois Rd", about:"Tincidunt dui ut ornare lectus sit amet est placerat in. Quam vulputate dignissim suspendisse in est ante in. Est ullamcorper eget nulla facilisi etiam dignissim diam. Tempus egestas sed sed risus pretium quam. Sit amet nulla facilisi morbi tempus iaculis."},
{id:"1188-brewing-co-john-day", name:"1188 Brewing Co",brewery_type:"brewpub",street:"141 E Main St", about:"Non sodales neque sodales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam"},
{id:"12-acres-brewing-company-killeshin",name:"12 Acres Brewing Company",brewery_type:"micro",street:"Unnamed Street", about:"In nulla posuere sollicitudin aliquam ultrices. Dignissim suspendisse in est ante in. Ut ornare lectus sit amet est placerat in egestas. Suscipit adipiscing bibendum est ultricies. Sed risus ultricies tristique nulla aliquet enim tortor at. Vulputate odio ut enim blandit. Semper viverra nam libero justo laoreet sit amet cursus. Viverra adipiscing at in tellus int"},{id:"12-gates-brewing-company-williamsville", name:"123 Gates Brewing Company",brewery_type:"brewpub",street:"80 Earhart Dr Ste 20",about:"Quam lacus suspendisse faucibus interdum. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Non sodales neque sodales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam vulputate dignissim. "},
{id:"12-west-brewing-company-gilbert",name:"12 West Brewing Company",brewery_type:"micro",street:"3000 E Ray Rd Bldg 6", about: "Quam lacus suspendisse faucibus interdum. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Non sodales neque sodales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam vulputate dignissim. "},
{id:"12-west-brewing-company-production-facility-mesa",name:"Broosters Co.",brewery_type :"micro", street: "1234 nowhere", about:"Dales ut etiam sit amet. Eget arcu dictum varius duis at consectetur lorem. Arcu felis bibendum ut tristique et. Sed sed risus pretium quam vulputate dignissim. Tincidunt dui ut ornare lectus sit amet est placerat in. Quam vulputate dignissim suspendisse in est ante in. "}]

const list = () => {
    return [...brewData]
};

const find = (id) =>{
    const post = brewData.find(post => post.id === id); //should the id always be a number? I got this data online
    return {...post};    //why does the return have to be an object? says its not iterable if its an array but whynot?


}


module.exports = {
    list: list, find: find
}